name: Documinder
description: Reminder developer to update document for code change
inputs:
  GITHUB_TOKEN:
    description: "Github Token for authentication"
    required: true
runs:
  using: "node12"
  main: "src/index.js"
#Slack notification is left to do
